[package]
name = "gfwd"
version = "0.1.0"
edition = "2024"

[dependencies]
zbus = "5.11"
derive_more = { version = "2.0.1", features = ["display"] }

relm4 = { version = "0.10", features = ["all", "gnome_47"] }
tracker = "0.2.2"
thiserror = "2.0.16"

gfwd-bus = { path = "../gfwd-bus", features = [
    "zone",
    "config_firewalld1",
    "config_zone",
    "config_service",
    "systemd",
    "config_icmptype",
    "config_ipset",
    "config_policies",
    "direct",
    "ipset",
    "policies",
    "config_helpers",
] }
