[package]
name = "gfwd-bus"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
zbus = "5.11"
zbus_macros = "5.11"
zvariant = "5.7"

[features]
config_direct = []
config_firewalld1 = []
config_helpers = []
config_icmptype = []
config_ipset = []
config_policies = []
config_service = []
config_zone = []
direct = []
firewalld1 = []
ipset = []
policies = []
zone = []
systemd = []
