[package]
name = "gfwd-bus"
version = "0.1.0"
edition = "2024"

[dependencies]
zbus = "5.19.0"
zbus_macros = "5.19.0"
zvariant = "5.14.0"
serde = { version = "1.0.229", features = ["derive"] }

[features]
config_direct = []
config_firewalld1 = []
config_helpers = []
config_icmptype = []
config_ipset = []
config_policies = []
config_service = []
config_zone = []
direct = []
firewalld1 = []
ipset = []
policies = []
zone = []
systemd = []
network_manager = []
